export const DOG_BREEDS = [
  "Mestizo",
  "Labrador Retriever",
  "Golden Retriever",
  "Pastor Alemán",
  "Bulldog",
  "Beagle",
  "Poodle / Caniche",
  "Chihuahua",
  "Yorkshire Terrier",
  "Boxer",
  "Rottweiler",
  "Dachshund / Salchicha",
  "Shih Tzu",
  "Husky Siberiano",
  "Cocker Spaniel",
  "Pitbull",
  "Otra",
  "No estoy seguro",
] as const;

export const CAT_BREEDS = [
  "Mestizo",
  "Persa",
  "Siamés",
  "Maine Coon",
  "Bengalí",
  "British Shorthair",
  "Ragdoll",
  "Sphynx",
  "Abisinio",
  "Otra",
  "No estoy seguro",
] as const;
